name: lambda-deploy

on:
  push:
    branches:
      - master

jobs:
  deploy_source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Create zip file
        run: |
          zip -r lambda.zip .
      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
          --region <AWS_REGION> \
          --function-name <LAMBDA_FUNCTION_NAME> \
          --zip-file fileb://lambda.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
