env:
  ACTIONS_STEP_DEBUG: true

name: Zip Source Code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Zip source code
        run: |
          zip -r source-code.zip .
